# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  preset-test:
    uses: ./.github/workflows/reusable-beman-install-test.yml
    with:
      image: ghcr.io/bemanproject/infra-containers-gcc:latest
      cxx_standard: 20
      main_header: identity.hpp
